# Generated by Django 3.2.4 on 2021-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210607_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='add_post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
